#include <iostream>
int main()
{
using namespace std;
cout << "What year was your house built?\n";
int year;
// cin >> year;
(cin>>year).get();// concatenate
cout << "What is its street address?\n";
//cin.get();// solution 1

char address[80];
cin.getline(address, 80);
cout << "Year built: " << year << endl;
cout << "Address: " << address << endl;
cout << "Done!\n";
return 0;
}

// Problem: you wont get the opportunity to enter the problem.
//cause:cin >> year leaved the  (newline generated by then enter) key word in the input stream 
//solution: 1)use cin.get() which takes of the newline and then then program can execute the cin.getline
//          2) can contenante the cin>> input